-- Insert all remaining airlines from the Airlines page
-- First, add the detailed ones we have data for from the dialog

-- United Airlines (we have detailed data)
INSERT INTO public.airlines (
  name, call_sign, pilot_group_size, fleet_size, description, pilot_union,
  fleet_info, bases, is_hiring, application_url, required_qualifications,
  preferred_qualifications, inside_scoop, most_junior_base, 
  most_junior_captain_hire_date, retirements_in_2025,
  fo_pay_year_1, fo_pay_year_5, fo_pay_year_10,
  captain_pay_year_1, captain_pay_year_5, captain_pay_year_10,
  additional_info, category
) VALUES 
(
  'United Airlines', 'United', '13,500+', 830,
  'Major American airline with extensive domestic and international route network across six continents.',
  'ALPA (Air Line Pilots Association)',
  '[{"type": "Boeing 777", "quantity": 96}, {"type": "Boeing 787", "quantity": 55}, {"type": "Airbus A350", "quantity": 45}, {"type": "Boeing 767", "quantity": 38}, {"type": "Boeing 757", "quantity": 21}, {"type": "Airbus A321", "quantity": 158}, {"type": "Boeing 737", "quantity": 247}, {"type": "Airbus A320/319", "quantity": 99}, {"type": "Embraer E175", "quantity": 71}]'::jsonb,
  '{"Chicago (ORD)", "Denver (DEN)", "Houston (IAH)", "Los Angeles (LAX)", "Newark (EWR)", "San Francisco (SFO)", "Washington DC (IAD)"}',
  true, 'https://careers.united.com/pilots',
  '{"Unrestricted ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "Current passport with 6+ months validity", "Legal right to work in US", "High school diploma or GED"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "100+ hours flight time in last 12 months"}',
  '{"Large fleet expansion planned", "Good career progression opportunities", "Strong international route network"}',
  'Newark (EWR)', 'May 2018', 380,
  '$106.92/hr', '$255.33/hr', '$279.85/hr',
  '$357.74/hr', '$371.58/hr', '$385.39/hr',
  '{"Major fleet renewal with new aircraft orders", "Competitive profit sharing program", "Extensive training facilities"}',
  'Majors'
),
(
  'American Airlines', 'American', '15,500+', 875,
  'World''s largest airline by fleet size and passengers carried, serving destinations across six continents from its hubs throughout the United States.',
  'APA (Allied Pilots Association)',
  '[{"type": "Boeing 777", "quantity": 47}, {"type": "Boeing 787", "quantity": 51}, {"type": "Airbus A330", "quantity": 24}, {"type": "Boeing 767", "quantity": 24}, {"type": "Boeing 757", "quantity": 34}, {"type": "Airbus A321", "quantity": 219}, {"type": "Boeing 737", "quantity": 304}, {"type": "Airbus A320/319", "quantity": 132}, {"type": "Embraer E175", "quantity": 40}]'::jsonb,
  '{"Dallas (DFW)", "Charlotte (CLT)", "Miami (MIA)", "Phoenix (PHX)", "Philadelphia (PHL)", "Chicago (ORD)", "Los Angeles (LAX)", "New York (LGA)", "Washington DC (DCA)"}',
  true, 'https://careers.aa.com/pilots',
  '{"ATP Certificate or meet ATP requirements", "Current First Class Medical", "Minimum 1,500 hours total time", "Multi-engine land rating", "Current passport valid for international travel", "Must be 23+ years old", "High school diploma or equivalent"}',
  '{"Bachelor''s degree from accredited institution", "1,000+ hours turbine time", "500+ hours turbine PIC time", "100+ hours flight time in last 12 months"}',
  '{"Largest airline in the world by fleet and revenue", "Strong domestic and international route network", "Competitive compensation and benefits package"}',
  'Miami (MIA)', 'February 2018', 520,
  '$115.75/hr', '$264.18/hr', '$291.19/hr',
  '$384.25/hr', '$398.45/hr', '$412.89/hr',
  '{"World''s largest airline with extensive global network", "Strong profit sharing and 401(k) matching", "Modern fleet with ongoing aircraft deliveries"}',
  'Majors'
),
(
  'Hawaiian Airlines', 'Hawaiian', '800+', 61,
  'Hawaii''s largest and longest-serving airline, connecting the Hawaiian Islands with destinations across the Pacific and mainland United States.',
  'ALPA (Air Line Pilots Association)',
  '[{"type": "Airbus A330", "quantity": 24}, {"type": "Airbus A321neo", "quantity": 18}, {"type": "Boeing 787", "quantity": 8}, {"type": "Boeing 717", "quantity": 20}, {"type": "ATR 72", "quantity": 8}]'::jsonb,
  '{"Honolulu (HNL)", "Kahului (OGG)", "Kona (KOA)", "Lihue (LIH)"}',
  true, 'https://careers.hawaiianairlines.com/pilots',
  '{"ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "500 hours multi-engine time", "Current passport with 6+ months validity", "Must be 21+ years old"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "International flying experience", "Pacific route experience"}',
  '{"Unique island-based operations", "Excellent quality of life in Hawaii", "Strong company culture and employee satisfaction"}',
  'Honolulu (HNL)', 'June 2019', 35,
  '$98.50/hr', '$185.75/hr', '$208.25/hr',
  '$275.80/hr', '$285.90/hr', '$298.45/hr',
  '{"Living in paradise with island-based operations", "Strong local community involvement", "Unique inter-island and trans-Pacific routes"}',
  'Majors'
),
(
  'Southwest Airlines', 'Southwest', '10,000+', 817,
  'Low-cost carrier known for point-to-point service, no-frills approach, and strong company culture. Operates exclusively Boeing 737 aircraft.',
  'SWAPA (Southwest Airlines Pilots'' Association)',
  '[{"type": "Boeing 737-700", "quantity": 215}, {"type": "Boeing 737-800", "quantity": 207}, {"type": "Boeing 737 MAX 7", "quantity": 30}, {"type": "Boeing 737 MAX 8", "quantity": 365}]'::jsonb,
  '{"Dallas (DAL)", "Houston (HOU)", "Phoenix (PHX)", "Las Vegas (LAS)", "Chicago (MDW)", "Baltimore (BWI)", "Denver (DEN)", "Oakland (OAK)", "Orlando (MCO)", "Atlanta (ATL)"}',
  true, 'https://careers.southwest.com/pilots',
  '{"ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "Boeing 737 type rating preferred", "Current passport", "Must be 23+ years old"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "Part 121 experience", "Boeing 737 experience"}',
  '{"Strong company culture and employee-friendly policies", "Single aircraft type simplifies operations", "Known for excellent work-life balance"}',
  'Atlanta (ATL)', 'April 2019', 295,
  '$102.35/hr', '$238.85/hr', '$263.75/hr',
  '$325.40/hr', '$338.90/hr', '$354.20/hr',
  '{"Profit sharing program with strong payouts", "Single fleet type reduces training complexity", "Strong company culture with employee ownership"}',
  'Majors'
);

-- Add detailed ULCC & Large Operators
INSERT INTO public.airlines (
  name, call_sign, pilot_group_size, fleet_size, description, pilot_union,
  fleet_info, bases, is_hiring, application_url, required_qualifications,
  preferred_qualifications, inside_scoop, most_junior_base, 
  most_junior_captain_hire_date, retirements_in_2025,
  fo_pay_year_1, fo_pay_year_5, fo_pay_year_10,
  captain_pay_year_1, captain_pay_year_5, captain_pay_year_10,
  additional_info, category
) VALUES 
(
  'Frontier', 'Frontier Flight', '1,800+', 137,
  'Ultra-low-cost carrier based in Denver, known for animal-themed aircraft liveries and focus on leisure travel markets.',
  'ALPA (Air Line Pilots Association)',
  '[{"type": "Airbus A320", "quantity": 74}, {"type": "Airbus A321", "quantity": 63}]'::jsonb,
  '{"Denver (DEN)", "Las Vegas (LAS)", "Orlando (MCO)", "Philadelphia (PHL)", "Phoenix (PHX)", "Tampa (TPA)", "Miami (MIA)"}',
  true, 'https://careers.flyfrontier.com/pilots',
  '{"ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "Multi-engine rating", "Current passport", "English proficiency"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "Airbus experience", "Part 121 experience"}',
  '{"Animal-themed aircraft with unique culture", "Growing route network", "Good entry point into Part 121 operations"}',
  'Denver (DEN)', 'September 2019', 18,
  '$88.00/hr', '$158.00/hr', '$178.00/hr',
  '$235.00/hr', '$248.00/hr', '$262.00/hr',
  '{"Unique animal-themed aircraft liveries", "Focus on leisure travel markets", "Denver-based with western US focus"}',
  'Ultra Low Cost Carriers & Large Operators'
),
(
  'Allegiant Air', 'Allegiant', '1,500+', 130,
  'Ultra-low-cost carrier specializing in leisure travel from small cities to vacation destinations with high-frequency, point-to-point service.',
  'IBT (International Brotherhood of Teamsters)',
  '[{"type": "Airbus A319", "quantity": 54}, {"type": "Airbus A320", "quantity": 76}]'::jsonb,
  '{"Las Vegas (LAS)", "Orlando (MCO)", "Phoenix (PHX)", "St. Pete (PIE)", "Cincinnati (CVG)", "Grand Rapids (GRR)"}',
  true, 'https://careers.allegiantair.com/pilots',
  '{"ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "Multi-engine land rating", "Current passport"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "Airbus experience", "Previous Part 121 experience"}',
  '{"Unique business model with leisure focus", "Good work-life balance", "Strong company performance"}',
  'Las Vegas (LAS)', 'November 2019', 12,
  '$86.00/hr', '$155.00/hr', '$175.00/hr',
  '$230.00/hr', '$245.00/hr', '$260.00/hr',
  '{"Leisure-focused route network", "Strong financial performance", "Unique small city to vacation destination model"}',
  'Ultra Low Cost Carriers & Large Operators'
),
(
  'JetBlue Airways', 'JetBlue', '4,500+', 289,
  'Low-cost carrier known for premium cabin experience, free WiFi, and focus on customer service with operations primarily on the East Coast.',
  'ALPA (Air Line Pilots Association)',
  '[{"type": "Airbus A220", "quantity": 63}, {"type": "Airbus A320", "quantity": 130}, {"type": "Airbus A321", "quantity": 96}]'::jsonb,
  '{"New York JFK (JFK)", "Boston (BOS)", "Fort Lauderdale (FLL)", "Orlando (MCO)", "Los Angeles (LAX)", "Long Beach (LGB)"}',
  true, 'https://careers.jetblue.com/pilots',
  '{"ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "Multi-engine rating", "Current passport", "English proficiency"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "Airbus experience", "Part 121 experience"}',
  '{"Known for excellent customer service culture", "Premium amenities in economy class", "Strong East Coast presence"}',
  'Fort Lauderdale (FLL)', 'July 2019', 42,
  '$95.00/hr', '$175.00/hr', '$195.00/hr',
  '$265.00/hr', '$280.00/hr', '$295.00/hr',
  '{"Premium service at low-cost carrier prices", "Strong brand recognition and customer loyalty", "Focus on technology and innovation"}',
  'Ultra Low Cost Carriers & Large Operators'
),
(
  'Breeze Airways', 'Breeze', '500+', 52,
  'Newest major US airline launched in 2021, focusing on underserved routes with modern aircraft and technology-forward approach.',
  'Non-unionized',
  '[{"type": "Embraer E190", "quantity": 27}, {"type": "Airbus A220", "quantity": 25}]'::jsonb,
  '{"Charleston (CHS)", "Norfolk (ORF)", "Tampa (TPA)", "New Orleans (MSY)", "Hartford (BDL)", "Providence (PVD)"}',
  true, 'https://careers.flybreeze.com/pilots',
  '{"ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "Multi-engine rating", "Current passport"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "Regional airline experience", "Embraer or Airbus experience"}',
  '{"Newest airline with modern fleet", "Focus on underserved markets", "Technology-forward operations"}',
  'Charleston (CHS)', 'March 2022', 0,
  '$92.00/hr', '$168.00/hr', '$188.00/hr',
  '$250.00/hr', '$265.00/hr', '$280.00/hr',
  '{"Founded by JetBlue''s founder David Neeleman", "Focus on point-to-point service", "Modern technology and guest experience"}',
  'Ultra Low Cost Carriers & Large Operators'
),
(
  'Sun Country Airlines', 'Sun Country', '700+', 50,
  'Low-cost carrier based in Minneapolis, offering scheduled passenger service, cargo, and charter operations with focus on leisure destinations.',
  'ALPA (Air Line Pilots Association)',
  '[{"type": "Boeing 737-700", "quantity": 11}, {"type": "Boeing 737-800", "quantity": 39}]'::jsonb,
  '{"Minneapolis (MSP)", "Dallas (DFW)", "Las Vegas (LAS)", "Phoenix (PHX)"}',
  true, 'https://careers.suncountry.com/pilots',
  '{"ATP Certificate", "Current First Class Medical", "Minimum 1,500 hours total time", "Multi-engine rating", "Current passport"}',
  '{"Bachelor''s degree", "1,000+ hours turbine time", "Boeing 737 experience", "Part 121 experience"}',
  '{"Strong Midwest presence", "Diverse operations including cargo and charter", "Family-friendly company culture"}',
  'Minneapolis (MSP)', 'October 2019', 8,
  '$89.00/hr', '$162.00/hr', '$182.00/hr',
  '$245.00/hr', '$260.00/hr', '$275.00/hr',
  '{"Based in Minneapolis with Midwest focus", "Diverse revenue streams beyond passenger service", "Strong operational performance"}',
  'Ultra Low Cost Carriers & Large Operators'
);

-- Add all Regional Carriers
INSERT INTO public.airlines (name, call_sign, pilot_group_size, fleet_size, description, pilot_union, category, is_hiring) VALUES 
('Air Wisconsin', 'Air Wisconsin', '600+', 75, 'Regional airline operating as United Express, based in Appleton, Wisconsin.', 'ALPA', 'Regional Carriers', true),
('Alaska Seaplanes', 'Alaska Seaplane', '50+', 15, 'Seaplane airline serving Alaska and the Pacific Northwest.', 'Non-unionized', 'Regional Carriers', true),
('Cape Air', 'Cape Air', '800+', 100, 'Regional airline serving New England, the Caribbean, and Micronesia.', 'Non-unionized', 'Regional Carriers', true),
('CommutAir', 'CommutAir', '800+', 90, 'Regional airline operating as United Express from bases across the eastern United States.', 'ALPA', 'Regional Carriers', true),
('Contour Airlines', 'Contour', '200+', 30, 'Regional airline providing essential air service to small communities.', 'Non-unionized', 'Regional Carriers', true),
('Denver Air Connection', 'Denver Air', '100+', 20, 'Regional airline serving Colorado and surrounding states.', 'Non-unionized', 'Regional Carriers', false),
('Elite Airways', 'Elite Air', '150+', 25, 'Regional charter and scheduled airline based in Portland, Maine.', 'Non-unionized', 'Regional Carriers', true),
('Endeavor Air', 'Endeavor', '4,500+', 180, 'Regional airline operating as Delta Connection from Minneapolis and New York hubs.', 'ALPA', 'Regional Carriers', true),
('Envoy Air', 'Envoy', '4,200+', 175, 'Regional airline operating as American Eagle from multiple hubs.', 'APA', 'Regional Carriers', true),
('ExpressJet Airlines', 'Express Jet', '2,800+', 120, 'Regional airline operating United Express and American Eagle flights.', 'ALPA', 'Regional Carriers', false),
('GoJet Airlines', 'GoJet', '1,800+', 85, 'Regional airline operating as United Express and Delta Connection.', 'ALPA', 'Regional Carriers', true),
('Grant Aviation', 'Grant Air', '200+', 35, 'Alaska-based regional airline serving remote communities.', 'Non-unionized', 'Regional Carriers', true),
('Great Lakes Airlines', 'Great Lakes', '300+', 40, 'Regional airline providing essential air service throughout the western United States.', 'Non-unionized', 'Regional Carriers', false),
('Horizon Air', 'Horizon', '2,200+', 85, 'Regional airline operating as Alaska Airlines flights from Seattle and Portland.', 'ALPA', 'Regional Carriers', true),
('Mesa Airlines', 'Mesa', '3,500+', 145, 'Regional airline operating as American Eagle and United Express.', 'ALPA', 'Regional Carriers', true),
('Ohana by Hawaiian', 'Ohana', '150+', 10, 'Regional airline serving Hawaiian inter-island routes.', 'ALPA', 'Regional Carriers', true),
('Piedmont Airlines', 'Piedmont', '3,200+', 140, 'Regional airline operating as American Eagle from Charlotte and Philadelphia.', 'ALPA', 'Regional Carriers', true),
('PSA Airlines', 'PSA', '3,800+', 155, 'Regional airline operating as American Eagle from multiple east coast hubs.', 'ALPA', 'Regional Carriers', true),
('Quantum Air', 'Quantum', '100+', 15, 'Regional charter airline based in Florida.', 'Non-unionized', 'Regional Carriers', false),
('Raven Alaska', 'Raven', '80+', 12, 'Alaska-based airline serving bush communities and cargo operations.', 'Non-unionized', 'Regional Carriers', true),
('Republic Airways', 'Republic', '5,500+', 220, 'Regional airline operating as American Eagle, Delta Connection, and United Express.', 'IBT', 'Regional Carriers', true),
('Seaborne Airlines', 'Seaborne', '200+', 25, 'Caribbean regional airline serving Puerto Rico and the Virgin Islands.', 'Non-unionized', 'Regional Carriers', true),
('Silver Airways', 'Silver', '800+', 50, 'Regional airline serving Florida, the Bahamas, and Caribbean.', 'Non-unionized', 'Regional Carriers', true),
('SkyWest', 'SkyWest', '12,000+', 450, 'Largest regional airline in North America operating for multiple major carriers.', 'ALPA', 'Regional Carriers', true),
('Star Air', 'Star Air', '150+', 20, 'Regional airline providing charter and scheduled services.', 'Non-unionized', 'Regional Carriers', false),
('Sterling Airways', 'Sterling', '100+', 15, 'Regional charter airline based in California.', 'Non-unionized', 'Regional Carriers', false);

-- Add all Fractional Carriers
INSERT INTO public.airlines (name, call_sign, pilot_group_size, fleet_size, description, pilot_union, category, is_hiring) VALUES 
('NetJets', 'NetJets', '3,500+', 750, 'World''s largest private jet company offering fractional aircraft ownership and jet card programs.', 'NJASAP', 'Fractional Carriers', true),
('Flexjet', 'Flexjet', '2,200+', 300, 'Fractional aircraft ownership and jet leasing company with a modern fleet.', 'IBT', 'Fractional Carriers', true),
('Flight Options', 'Flight Options', '1,800+', 200, 'Fractional ownership program offering access to a diverse fleet of aircraft.', 'IBT', 'Fractional Carriers', true),
('Directional Aviation', 'Directional', '800+', 120, 'Aviation services company including fractional ownership and charter operations.', 'Non-unionized', 'Fractional Carriers', true),
('Executive AirShare', 'AirShare', '400+', 60, 'Fractional aircraft ownership company based in Kansas City.', 'Non-unionized', 'Fractional Carriers', true),
('PlaneSense', 'PlaneSense', '300+', 45, 'Fractional ownership program specializing in Pilatus PC-12 aircraft.', 'Non-unionized', 'Fractional Carriers', true),
('XOJet', 'XOJet', '600+', 90, 'On-demand private jet charter and membership company.', 'Non-unionized', 'Fractional Carriers', false),
('JetSuite', 'JetSuite', '200+', 30, 'Private jet charter company offering on-demand and membership programs.', 'Non-unionized', 'Fractional Carriers', false),
('Airshare', 'Airshare', '250+', 40, 'Fractional aircraft ownership company based in Kansas.', 'Non-unionized', 'Fractional Carriers', true),
('Wheels Up', 'Wheels Up', '1,200+', 180, 'Private aviation company offering membership-based flying solutions.', 'Non-unionized', 'Fractional Carriers', true),
('VistaJet', 'Vista', '2,800+', 350, 'Global business aviation company offering private jet flights worldwide.', 'Non-unionized', 'Fractional Carriers', true),
('Jet Linx', 'Jet Linx', '800+', 120, 'Private jet management and jet card company with locations nationwide.', 'Non-unionized', 'Fractional Carriers', true);

-- Add all Cargo Airlines
INSERT INTO public.airlines (name, call_sign, pilot_group_size, fleet_size, description, pilot_union, category, is_hiring) VALUES 
('21 Air, LLC', '21 Air', '50+', 8, 'Cargo airline specializing in overnight express delivery services.', 'Non-unionized', 'Cargo', true),
('ABX Air', 'ABX', '1,200+', 75, 'Cargo airline operating for DHL and other freight companies.', 'ALPA', 'Cargo', true),
('Air Cargo Carriers', 'Night Cargo', '400+', 50, 'Cargo airline providing overnight freight services across the United States.', 'Non-unionized', 'Cargo', true),
('Air Transport International', 'ATI', '800+', 45, 'Cargo airline operating worldwide freight services for major integrators.', 'IBT', 'Cargo', true),
('Alaska Central Express', 'ACE Air', '200+', 25, 'Alaska-based cargo airline serving remote communities and freight operations.', 'Non-unionized', 'Cargo', true),
('Aloha Air Cargo', 'Aloha Cargo', '150+', 12, 'Hawaiian cargo airline serving inter-island and mainland freight routes.', 'Non-unionized', 'Cargo', true),
('Alpine Air', 'Alpine Air', '100+', 15, 'Charter and cargo airline based in Utah serving the western United States.', 'Non-unionized', 'Cargo', true),
('Ameriflight', 'Amflight', '1,800+', 200, 'Large cargo airline providing freight services throughout North America.', 'IBT', 'Cargo', true),
('Amerijet International', 'Amerijet', '600+', 35, 'International cargo airline serving the Caribbean and Latin America.', 'IBT', 'Cargo', true),
('Ameristar Air Cargo, Inc.', 'Ameristar', '300+', 25, 'Cargo airline specializing in time-sensitive and oversized freight.', 'Non-unionized', 'Cargo', true),
('Atlas Air', 'Atlas', '2,800+', 120, 'Global cargo airline operating Boeing 747 and 767 freighters worldwide.', 'ALPA', 'Cargo', true),
('Bemidji Aviation Services, Inc.', 'Bemidji', '80+', 12, 'Regional cargo airline serving the upper midwest United States.', 'Non-unionized', 'Cargo', true),
('CSA Air', 'CSA Air', '60+', 8, 'Cargo airline providing freight services in the southeastern United States.', 'Non-unionized', 'Cargo', false),
('Empire Airlines', 'Empire Air', '400+', 35, 'Cargo airline operating freight services for FedEx and other carriers.', 'ALPA', 'Cargo', true),
('Encore Air Cargo', 'Encore', '200+', 20, 'Cargo airline specializing in express delivery and charter freight services.', 'Non-unionized', 'Cargo', true),
('Everts Air Cargo', 'Everts', '300+', 25, 'Alaska-based cargo airline serving remote communities and freight operations.', 'Non-unionized', 'Cargo', true),
('FedEx Express', 'FedEx', '5,500+', 680, 'World''s largest express transportation company with extensive cargo operations.', 'ALPA', 'Cargo', true),
('Freight Runners Express', 'Freight Runners', '150+', 18, 'Cargo airline providing overnight freight services in the United States.', 'Non-unionized', 'Cargo', true),
('IFL Group', 'IFL', '200+', 15, 'Cargo airline providing freight and charter services across North America.', 'Non-unionized', 'Cargo', true),
('Kalitta Air', 'Kalitta', '1,400+', 85, 'Cargo airline operating Boeing 747 freighters for international freight services.', 'ALPA', 'Cargo', true),
('Kalitta Charters II', 'Kalitta Charter', '200+', 12, 'Charter cargo airline specializing in heavy lift and oversized freight.', 'Non-unionized', 'Cargo', true),
('Key Lime Air', 'Key Lime', '400+', 45, 'Cargo airline providing freight services throughout the eastern United States.', 'Non-unionized', 'Cargo', true),
('Lynden Air Cargo', 'Lynden', '250+', 20, 'Alaska-based cargo airline serving remote communities and freight operations.', 'Non-unionized', 'Cargo', true),
('Mountain Air Cargo', 'Mountain Air', '800+', 85, 'Cargo airline operating freight services for FedEx and UPS.', 'ALPA', 'Cargo', true),
('National Airlines', 'National Cargo', '600+', 45, 'Cargo airline providing international freight services worldwide.', 'IBT', 'Cargo', true),
('Northern Air Cargo', 'Northern Air', '400+', 35, 'Alaska-based cargo airline serving communities throughout Alaska.', 'Non-unionized', 'Cargo', true),
('Quest Diagnostics', 'Quest Air', '100+', 15, 'Medical cargo airline providing laboratory specimen transportation.', 'Non-unionized', 'Cargo', true),
('Ryan Air', 'Ryan Air', '150+', 20, 'Cargo airline providing freight services in the midwestern United States.', 'Non-unionized', 'Cargo', true),
('SkyLease Cargo', 'SkyLease', '300+', 25, 'International cargo airline operating Boeing 747 freighters.', 'Non-unionized', 'Cargo', true),
('Transair', 'Transair', '200+', 18, 'Hawaiian cargo airline serving inter-island freight operations.', 'Non-unionized', 'Cargo', true),
('United Parcel Service', 'UPS', '3,200+', 280, 'Global package delivery and logistics company with extensive cargo operations.', 'IPA', 'Cargo', true),
('USA Jet Airlines', 'USA Jet', '300+', 25, 'Cargo airline providing overnight freight and charter services.', 'Non-unionized', 'Cargo', true),
('Western Global Airlines', 'Western Global', '500+', 35, 'International cargo airline providing freight services worldwide.', 'Non-unionized', 'Cargo', true),
('Wiggins Airways', 'Wiggins', '200+', 20, 'Cargo airline providing freight services in the northeastern United States.', 'Non-unionized', 'Cargo', true);