-- Add narrow body and wide body pay scale columns for First Officers
ALTER TABLE airlines 
ADD COLUMN fo_narrowbody_pay_year_1 text,
ADD COLUMN fo_narrowbody_pay_year_2 text,
ADD COLUMN fo_narrowbody_pay_year_3 text,
ADD COLUMN fo_narrowbody_pay_year_4 text,
ADD COLUMN fo_narrowbody_pay_year_5 text,
ADD COLUMN fo_narrowbody_pay_year_6 text,
ADD COLUMN fo_narrowbody_pay_year_7 text,
ADD COLUMN fo_narrowbody_pay_year_8 text,
ADD COLUMN fo_narrowbody_pay_year_9 text,
ADD COLUMN fo_narrowbody_pay_year_10 text,
ADD COLUMN fo_widebody_pay_year_1 text,
ADD COLUMN fo_widebody_pay_year_2 text,
ADD COLUMN fo_widebody_pay_year_3 text,
ADD COLUMN fo_widebody_pay_year_4 text,
ADD COLUMN fo_widebody_pay_year_5 text,
ADD COLUMN fo_widebody_pay_year_6 text,
ADD COLUMN fo_widebody_pay_year_7 text,
ADD COLUMN fo_widebody_pay_year_8 text,
ADD COLUMN fo_widebody_pay_year_9 text,
ADD COLUMN fo_widebody_pay_year_10 text;

-- Add narrow body and wide body pay scale columns for Captains
ALTER TABLE airlines 
ADD COLUMN captain_narrowbody_pay_year_1 text,
ADD COLUMN captain_narrowbody_pay_year_2 text,
ADD COLUMN captain_narrowbody_pay_year_3 text,
ADD COLUMN captain_narrowbody_pay_year_4 text,
ADD COLUMN captain_narrowbody_pay_year_5 text,
ADD COLUMN captain_narrowbody_pay_year_6 text,
ADD COLUMN captain_narrowbody_pay_year_7 text,
ADD COLUMN captain_narrowbody_pay_year_8 text,
ADD COLUMN captain_narrowbody_pay_year_9 text,
ADD COLUMN captain_narrowbody_pay_year_10 text,
ADD COLUMN captain_widebody_pay_year_1 text,
ADD COLUMN captain_widebody_pay_year_2 text,
ADD COLUMN captain_widebody_pay_year_3 text,
ADD COLUMN captain_widebody_pay_year_4 text,
ADD COLUMN captain_widebody_pay_year_5 text,
ADD COLUMN captain_widebody_pay_year_6 text,
ADD COLUMN captain_widebody_pay_year_7 text,
ADD COLUMN captain_widebody_pay_year_8 text,
ADD COLUMN captain_widebody_pay_year_9 text,
ADD COLUMN captain_widebody_pay_year_10 text;