// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uezrpgdbeemoqrxuzaln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlenJwZ2RiZWVtb3FyeHV6YWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjUwMzcsImV4cCI6MjA2NjgwMTAzN30.8Rab0ISBx6CTGnEeItVAhk0vwOHgrPPFv6ooZ2Sy2Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});