// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odglrbnigjqqanvyklyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZ2xyYm5pZ2pxcWFudnlrbHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjIzOTYsImV4cCI6MjA3MjQzODM5Nn0.-dNjQVzujIiJExmx2ESFt1bogo6kuBHF5Yx2Ez0XAcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});